### ISSUE TITLE
improve hit boxes

### ISSUE THREAD

**Issue by JeroUwU** [pege22/pege_source_main#13]
the hit boxes are to big or to short
causes some bugs also

**Comment by LUIS9799** [comment]
Can you make a list and send videos showing the bugs? Then assignees will analize bugs and try a solution for them, also hitboxes scale keeps in the linear sprite/resource size, it means that it depends on assests borders, you can change assests size and then try object inclusion

**Comment by LUIS9799** [comment]
Not fixed yet, help wanted.

**Comment by LUIS9799** [comment]
https://user-images.githubusercontent.com/68512719/189506130-96bab062-f7e9-4fd6-b077-62df02a11690.mp4

**Comment by LUIS9799** [comment]
Improved again

**Comment by LUIS9799** [comment]
Impoved
