### ISSUE TITLE
Señalización de controles

### ISSUE THREAD

**Issue by JeroUwU** [pege22/pege_source_main#22]
señalizar de alguna forma los controles para mas claridad

**Comment by LUIS9799** [comment]
Right, Working.

**Comment by LUIS9799** [comment]
Esta función fue añadida por petición de varios testers, sin embargo dejaré el issue abierto para recibir opiniones por parte de @JeroUwU @Juanesitopege @thecreeperbot @Masterpotter999 @PabloCarrascoB

**Comment by LUIS9799** [comment]
Cerrada, utilizar discuciones.
