### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by JeroUwU** [pege22/pege_source_main#53]
Si estas en una esquina te puedes quedar atascado con una dificultad demasiado alta de salir

**Comment by LUIS9799** [comment]
Investigando.

**Comment by LUIS9799** [comment]
Continúa en investigación

**Comment by LUIS9799** [comment]
Error identificado, el vector de la hitbox fue modificado y ahora no debería tener problemas, sin embargo los @Bugstesters @JeroUwU @thecreeperbot etc.. se les recomienda verificar cualquier error relacionado

**Comment by LUIS9799** [comment]
El servidor de developers trae consigo una solución al error que será implementada a producción en breve ;)
